### ISSUE TITLE
Start button doesn't appear in Chrome (Blink) but works in Firefox (Gecko)

### ISSUE THREAD

**Issue by duttakapil** [coderplex-org/flappyQuery#3]
So as most of you know, the Start button that is supposed to appear at the center of the play area, doesn't appear in Chrome, or any browser that uses [Blink web engine](https://en.wikipedia.org/wiki/Blink_%28web_engine%29). This is because of the silly `left-margin : -100%;` which was put in for it to work properly in Firefox, and that is the interesting part. The button appears fine in Firefox, or the [Gecko web engine](https://en.wikipedia.org/wiki/Gecko_%28software%29). 
![Chrome with margin-left](https://cloud.githubusercontent.com/assets/6577624/18622958/90ae9e44-7e54-11e6-9a1b-520c824b9a0c.png)
![Chrome without margin left](https://cloud.githubusercontent.com/assets/6577624/18622969/bf931cbc-7e54-11e6-841c-4cc711729aa9.png)

So does anyone wanna get to the bottom of this and figure out what's exactly going on?
If you're new to open source, this is your opportunity to contribute to this project. If you need any help, let us know in the comments below.

**Comment by sudheerdarla** [comment]
Hey...I will try this one. @duttakapil
